//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoExam
{
    using System;
    using System.Collections.Generic;
    
    public partial class Material
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Material()
        {
            this.Postavki = new HashSet<Postavki>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public int Tip { get; set; }
        public string Image { get; set; }
        public int Price { get; set; }
        public int KolVoNaSklad { get; set; }
        public int MinKol { get; set; }
        public int KolvoUpakov { get; set; }
        public int EdIzm { get; set; }

        public string Ed
        {
            get
            {
                return EdinIzmer.EdinIzmereniya;
            }
        }
        public string MatTip
        {
            get
            {
                return TipMaterial.Tip;
            }
        }
    
        public virtual EdinIzmer EdinIzmer { get; set; }
        public virtual TipMaterial TipMaterial { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Postavki> Postavki { get; set; }
    }
}
