//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoExam
{
    using System;
    using System.Collections.Generic;
    
    public partial class Postavshiki
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Postavshiki()
        {
            this.Postavki = new HashSet<Postavki>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public int TipPostav { get; set; }
        public string INN { get; set; }
        public int Reiting { get; set; }
        public System.DateTime DataNachalaRabot { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Postavki> Postavki { get; set; }
        public virtual TipPostavshika TipPostavshika { get; set; }
    }
}
